version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - SECRET_KEY=django-super-secret-key-1234567890
      - DEBUG=True
    restart: always
